openapi: 3.0.0
info:
  title: API Gateway - Aseguradora
  version: 1.0.0
  description: API para obtener cotizaciones de seguros.

servers:
  - url: http://localhost:3000
    description: Servidor Local

tags:
  - name: Cotizaciones
  - name: Autenticación

paths:
  /api/auth/{compania}:
    post:
      tags:
        - Autenticación
      summary: Obtener token JWT para una compañía
      description: Retorna un token de autenticación JWT para la aseguradora especificada.
      parameters:
        - in: path
          name: compania
          required: true
          schema:
            type: string
            enum: [RUS, EXPERTA, MERCANTIL_ANDINA, SAN_CRISTOBAL, INTEGRITY]
          description: Nombre de la compañía aseguradora
      responses:
        '200':
          description: Token JWT obtenido con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6...
        '500':
          description: Error al autenticar
#  /api/cotizar/todas:
#    post:
#      summary: Obtener cotizaciones de todas las aseguradoras
#      tags:
#        - Cotizaciones
#      description: |
#        Este endpoint unifica las cotizaciones de las aseguradoras RUS, EXPERTA, San Cristóbal, Integrity y Mercantil Andina. 
#        Se envía un único body con los datos del vehículo y el tomador, y el sistema responde con los resultados individuales por compañía.
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                codInfoAuto:
#                  type: integer
#                  example: 170838
#                anio:
#                  type: integer
#                  example: 2022
#                sumaAsegurada:
#                  type: number
#                  example: 3250000
#                codigoPostal:
#                  type: string
#                  example: "1407"
#                uso:
#                  type: string
#                  example: "Particular"
#                infoauto:
#                  type: string
#                  example: "460913"
#                fechaNacimiento:
#                  type: string
#                  format: date
#                  example: "1982-08-15"
#                sexo:
#                  type: string
#                  example: "M"
#                localidad:
#                  type: string
#                  example: "000716"
#                provincia:
#                  type: string
#                  example: "01"
#                email:
#                  type: string
#                  example: "test@correo.com"
#                nombre:
#                  type: string
#                  example: "Lucas"
#                apellido:
#                  type: string
#                  example: "Pérez"
#                numeroDocumento:
#                  type: string
#                  example: "30123456"
#      responses:
#        "200":
#          description: Respuesta con cotizaciones por aseguradora
#          content:
#            application/json:
#              schema:
#                type: array
#                items:
#                  type: object
#                  properties:
#                    aseguradora:
#                      type: string
#                      example: "RUS"
#                    resultado:
#                      type: object
#        "500":
#          description: Error en el procesamiento de alguna aseguradora

#  /api/cotizar/rus:
#    post:
#      summary: Cotizar seguro en RUS
#      tags:
#        - Cotizaciones
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                codInfoAuto:
#                  type: integer
#                  example: 170838
#                anio:
#                  type: integer
#                  example: 2022
#                sumaAsegurada:
#                  type: number
#                  example: 3250000
#                codigoPostal:
#                  type: string
#                  example: "1407"
#                uso:
#                  type: string
#                  example: "Particular"
#      responses:
#        "200":
#          description: Cotización obtenida exitosamente
#        "500":
#          description: Error interno del servidor

#  /api/cotizar/experta:
#    post:
#      summary: Cotizar seguro en EXPERTA
#      tags:
#        - Cotizaciones
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                codInfoAuto:
#                  type: integer
#                  example: 360720
#                anio:
#                  type: integer
#                  example: 2013
#                modelo:
#                  type: string
#                  example: "DUSTER"
#                marca:
#                  type: string
#                  example: "RENAULT"
#                version:
#                  type: string
#                  example: "1.6 4X2 TECH ROAD CON AC, 05 PUERTAS"
#                fechaVigencia:
#                  type: string
#                  example: "01/02/2023"
#                productor:
#                  type: string
#                  example: "972"
#      responses:
#        "200":
#          description: Cotización obtenida exitosamente
#        "500":
#          description: Error interno del servidor

#  /api/cotizar/san-cristobal:
#    post:
#      summary: Cotizar seguro en San Cristóbal
#      tags:
#        - Cotizaciones
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                infoauto:
#                  type: string
#                  example: "460913"
#                anio:
#                  type: integer
#                  example: 2021
#                sumaAsegurada:
#                  type: number
#                  example: 3252000
#                uso:
#                  type: string
#                  example: "Particular"
#      responses:
#        "200":
#          description: Cotización obtenida exitosamente
#        "500":
#          description: Error interno del servidor

#  /api/cotizar/integrity:
#    post:
#      summary: Cotizar seguro en Integrity
#      tags:
#        - Cotizaciones
#      requestBody:
#        required: true
#        content:
#          application/json:
#            schema:
#              type: object
#              properties:
#                marca:
#                  type: string
#                  example: "18"
#                modelo:
#                  type: string
#                  example: "759"
#                anio:
#                  type: integer
#                  example: 2023
#                sumaAsegurada:
#                  type: number
#                  example: 47500000
#      responses:
#        "200":
#          description: Cotización obtenida exitosamente
#        "500":
#          description: Error interno del servidor