openapi: 3.0.0
info:
  title: API Gateway - Aseguradora
  version: 1.0.0
  description: API para obtener cotizaciones de seguros.

servers:
  - url: http://localhost:3000
    description: Servidor Local

paths:
  /api/datos:
    get:
      summary: Obtener datos de aseguradoras
      description: Retorna información de aseguradoras en un formato estandarizado.
      responses:
        "200":
          description: Datos de las aseguradoras
          content:
            application/json:
              schema:
                type: object
                properties:
                  source1:
                    type: object
                  source2:
                    type: object
        "500":
          description: Error interno del servidor

  /api/jwt-data:
    get:
      summary: Obtener datos protegidos con JWT
      description: Retorna datos desde una API externa que requiere autenticación JWT.
      responses:
        "200":
          description: Datos obtenidos con autenticación JWT
          content:
            application/json:
              schema:
                type: object
        "401":
          description: No autorizado
        "500":
          description: Error interno del servidor
