require('dotenv').config();

console.log("🔍 Configuración cargada:");
console.log("JWT_API_LOGIN:", process.env.JWT_API_LOGIN);
console.log("JWT_API_DATA:", process.env.JWT_API_DATA);
console.log("JWT_USER:", process.env.JWT_USER);
console.log("JWT_PASS:", process.env.JWT_PASS);

module.exports = {
    JWT_API_LOGIN: process.env.JWT_API_LOGIN,
    JWT_API_DATA: process.env.JWT_API_DATA,
    JWT_USER: process.env.JWT_USER,
    JWT_PASS: process.env.JWT_PASS,
    RUS_API_URL: process.env.RUS_API_URL,
    RUS_API_URL_TEST: process.env.RUS_API_URL_TEST, 
    RUS_API_USERNAME: process.env.RUS_API_USERNAME,
    RUS_API_PASSWORD: process.env.RUS_API_PASSWORD,

    INTEGRITY_API_URL: process.env.INTEGRITY_API_URL,
    INTEGRITY_PRODUCTOR: process.env.INTEGRITY_PRODUCTOR,
    INTEGRITY_TICKET: process.env.INTEGRITY_TICKET,

    MERCANTIL_ANDINA_API_LOGIN_URL: process.env.MERCANTIL_ANDINA_API_LOGIN_URL,
    MERCANTIL_ANDINA_API_URL: process.env.MERCANTIL_ANDINA_API_URL,
    MERCANTIL_ANDINA_API_USERNAME: process.env.MERCANTIL_ANDINA_API_USERNAME,
    MERCANTIL_ANDINA_API_PASSWORD: process.env.MERCANTIL_ANDINA_API_PASSWORD,
    MERCANTIL_ANDINA_API_CLIENT_ID: process.env.MERCANTIL_ANDINA_API_CLIENT_ID,
    MERCANTIL_ANDINA_API_SUBSCRIPTION_PRIMARY_KEY: process.env.MERCANTIL_ANDINA_API_SUBSCRIPTION_PRIMARY_KEY,
   
    SAN_CRISTOBAL_API_URL: process.env.SAN_CRISTOBAL_API_URL,
    SAN_CRISTOBAL_API_LOGIN_URL: process.env.SAN_CRISTOBAL_API_LOGIN_URL,
    SAN_CRISTOBAL_API_USERNAME: process.env.SAN_CRISTOBAL_API_USERNAME,
    SAN_CRISTOBAL_API_PASSWORD: process.env.SAN_CRISTOBAL_API_PASSWORD,
    SAN_CRISTOBAL_API_CODE: process.env.SAN_CRISTOBAL_API_CODE,

    EXPERTA_API_URL: process.env.EXPERTA_API_URL,
    EXPERTA_API_USERNAME: process.env.EXPERTA_API_USERNAME,
    EXPERTA_API_PASSWORD: process.env.EXPERTA_API_PASSWORD,
    EXPERTA_API_KEY: process.env.EXPERTA_API_KEY
};
